//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongDong_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING_DETAIL_PEOPLE
    {
        public int BOOKING_DETAIL_PEOPLE_ID { get; set; }
        public Nullable<int> BOOKING_ID { get; set; }
        public string NAME { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
    
        public virtual BOOKING BOOKING { get; set; }
    }
}
