//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongDong_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING()
        {
            this.BOOKING_DETAIL = new HashSet<BOOKING_DETAIL>();
            this.BOOKING_DETAIL_PEOPLE = new HashSet<BOOKING_DETAIL_PEOPLE>();
        }
    
        public int BOOKING_ID { get; set; }
        public Nullable<int> QUANTITY_ADULT { get; set; }
        public Nullable<int> QUANTITY_CHILD { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public string STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING_DETAIL> BOOKING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING_DETAIL_PEOPLE> BOOKING_DETAIL_PEOPLE { get; set; }
    }
}
