//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongDong_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int FEEDBACK_ID { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FEEDBACK_DATE { get; set; }
        public string FEEDBACK_TEXT { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
