//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongDong_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThongDongDBContext : DbContext
    {
        public ThongDongDBContext()
            : base("name=ThongDongDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<BOOKING> BOOKINGs { get; set; }
        public virtual DbSet<BOOKING_DETAIL> BOOKING_DETAIL { get; set; }
        public virtual DbSet<BOOKING_DETAIL_PEOPLE> BOOKING_DETAIL_PEOPLE { get; set; }
        public virtual DbSet<DESTINATION> DESTINATIONs { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACKs { get; set; }
        public virtual DbSet<GUIDE> GUIDEs { get; set; }
        public virtual DbSet<ROLE_MASTER> ROLE_MASTER { get; set; }
        public virtual DbSet<TOUR> TOURs { get; set; }
        public virtual DbSet<USER_ROLES_MAPPING> USER_ROLES_MAPPING { get; set; }
    }
}
