//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongDong_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ROLES_MAPPING
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ROLE_MASTER ROLE_MASTER { get; set; }
    }
}
